services:
    laravel-app:
        build:
            context: .
            dockerfile: docker/Dockerfile
            args:
              DEBUG: 1
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8080}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - laravel-network
        depends_on:
            - mariadb

    mariadb:
        image: mariadb:10.6
        restart: unless-stopped
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        networks:
            - laravel-network


networks:
    laravel-network:
        driver: bridge

volumes:
    mariadb:
        driver: local
